# https://github.com/behaviorbot/request-info

requestInfoReplyComment: >
  We would appreciate it if you could provide us with more info about this issue/pr!
  Se our docs about Pull Requests https://niteo.gitbook.io/handbook/3_development/git#pull-request
