"""WPLang definition constants."""
#  !!! This file is autogenerated !!!
#  !!! See .codegen/update_const.py for details. !!!

from typing import List

WPLANGS: List[str] = [
    "en_US",  # WordPress base
    "af",  # Afrikaans
    "ar",  # Arabic
    "ary",  # Moroccan Arabic
    "as",  # Assamese
    "azb",  # South Azerbaijani
    "az",  # Azerbaijani
    "bel",  # Belarusian
    "bg_BG",  # Bulgarian
    "bn_BD",  # Bengali
    "bo",  # Tibetan
    "bs_BA",  # Bosnian
    "ca",  # Catalan
    "ceb",  # Cebuano
    "cs_CZ",  # Czech
    "cy",  # Welsh
    "da_DK",  # Danish
    "de_DE_formal",  # German (Formal)
    "de_DE",  # German
    "de_CH",  # German (Switzerland)
    "de_CH_informal",  # German (Switzerland, Informal)
    "dzo",  # Dzongkha
    "el",  # Greek
    "en_AU",  # English (Australia)
    "en_NZ",  # English (New Zealand)
    "en_CA",  # English (Canada)
    "en_GB",  # English (UK)
    "en_ZA",  # English (South Africa)
    "eo",  # Esperanto
    "es_AR",  # Spanish (Argentina)
    "es_ES",  # Spanish (Spain)
    "es_MX",  # Spanish (Mexico)
    "es_CO",  # Spanish (Colombia)
    "es_GT",  # Spanish (Guatemala)
    "es_CR",  # Spanish (Costa Rica)
    "es_PE",  # Spanish (Peru)
    "es_CL",  # Spanish (Chile)
    "es_VE",  # Spanish (Venezuela)
    "et",  # Estonian
    "eu",  # Basque
    "fa_IR",  # Persian
    "fi",  # Finnish
    "fr_CA",  # French (Canada)
    "fr_FR",  # French (France)
    "fr_BE",  # French (Belgium)
    "fur",  # Friulian
    "gd",  # Scottish Gaelic
    "gl_ES",  # Galician
    "gu",  # Gujarati
    "haz",  # Hazaragi
    "he_IL",  # Hebrew
    "hi_IN",  # Hindi
    "hr",  # Croatian
    "hu_HU",  # Hungarian
    "hy",  # Armenian
    "id_ID",  # Indonesian
    "is_IS",  # Icelandic
    "it_IT",  # Italian
    "ja",  # Japanese
    "jv_ID",  # Javanese
    "ka_GE",  # Georgian
    "kab",  # Kabyle
    "kk",  # Kazakh
    "km",  # Khmer
    "ko_KR",  # Korean
    "ckb",  # Kurdish (Sorani)
    "lo",  # Lao
    "lt_LT",  # Lithuanian
    "lv",  # Latvian
    "mk_MK",  # Macedonian
    "ml_IN",  # Malayalam
    "mn",  # Mongolian
    "mr",  # Marathi
    "ms_MY",  # Malay
    "my_MM",  # Myanmar (Burmese)
    "nb_NO",  # Norwegian (Bokmål)
    "ne_NP",  # Nepali
    "nl_BE",  # Dutch (Belgium)
    "nl_NL",  # Dutch
    "nl_NL_formal",  # Dutch (Formal)
    "nn_NO",  # Norwegian (Nynorsk)
    "oci",  # Occitan
    "pa_IN",  # Punjabi
    "pl_PL",  # Polish
    "ps",  # Pashto
    "pt_PT",  # Portuguese (Portugal)
    "pt_BR",  # Portuguese (Brazil)
    "pt_PT_ao90",  # Portuguese (Portugal, AO90)
    "rhg",  # Rohingya
    "ro_RO",  # Romanian
    "ru_RU",  # Russian
    "sah",  # Sakha
    "si_LK",  # Sinhala
    "sk_SK",  # Slovak
    "sl_SI",  # Slovenian
    "sq",  # Albanian
    "sr_RS",  # Serbian
    "sv_SE",  # Swedish
    "szl",  # Silesian
    "ta_IN",  # Tamil
    "te",  # Telugu
    "th",  # Thai
    "tl",  # Tagalog
    "tr_TR",  # Turkish
    "tt_RU",  # Tatar
    "tah",  # Tahitian
    "ug_CN",  # Uighur
    "uk",  # Ukrainian
    "ur",  # Urdu
    "uz_UZ",  # Uzbek
    "vi",  # Vietnamese
    "zh_HK",  # Chinese (Hong Kong)
    "zh_TW",  # Chinese (Taiwan)
    "zh_CN",  # Chinese (China)
]
