"""Generate const enums from WordPress API file to avoid human errors.

Usage: make codegen
"""

from pathlib import Path

import requests
import structlog

log = structlog.getLogger(__name__)

HEADER = '''\
"""WPLang definition constants."""
#  !!! This file is autogenerated !!!
#  !!! See .codegen/update_const.py for details. !!!

from typing import List


'''

# WPLang model
model = []
model.append("WPLANGS: List[str] = [")
log.info("Fetching info")
res = requests.get(f"http://api.wordpress.org/translations/core/1.0/")
res.raise_for_status()
for translation in res.json()["translations"]:
    wplang = translation["language"]
    log.info("Adding", language=wplang, name=translation["english_name"])
    model.append(f'  "{wplang}",')  # noqa: C408
model.append("]")
Path(".travis/wplang.py").write_text(HEADER + "\n".join(model))
