# Local Standards
woo/woocommerce_default_country: 'BR' # Country code https://github.com/woocommerce/woocommerce/blob/master/i18n/countries.php
wp/date_format: 'm/d/Y' # "d/m/Y", "Y-m-d", "F j, Y" for December 1, 2020
wp/time_format: 'H:i' # "H:i" for 24-hour clock, "g:i A" for 12-hour clock
wp/start_of_week: '7' # 1= Monday, 7=Sunday
wp/timezone_string: 'America/Sao_Paulo' # Timezone string https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
wp/blog_charset: 'UTF-8'
wp/WPLANG: 'pt_BR' # WordPress Locale Codes: https://wpastra.com/docs/complete-list-wordpress-locale-codes/
woo/woocommerce_weight_unit: 'kg' # Measurements weight unit kg, g, lbs, oz
woo/woocommerce_dimension_unit: 'cm' # Measurements dimension unit m, cm, mm, in, yd
# Currency options
woo/woocommerce_currency: 'BRL' # Currency code https://www.iban.com/currency-codes.html
woo/woocommerce_currency_pos: 'left_space' # Currency position: left, left_space, right, right_space
woo/woocommerce_price_thousand_sep: ',' # Thousand separator
woo/woocommerce_price_decimal_sep: '.' # Decimal separator
woo/woocommerce_price_num_decimals: '2' # Number of decimals

# Tax rates
woo/woocommerce_tax_classes: '' # If more than one reduced rate add '\nReduced rate 2'
wootax/1: # Standard rate
    country: 'BR'
    state: ''
    rate: '17.0000'
    name: 'ICMS' # Translate
    priority: '1'
    compound: '0'
    shipping: '0'
    order: '0'
    class: 'standard-rate'
    locations: {  }

# Payments - Direct bank transfer
woo/woocommerce_bacs_settings:
    enabled: 'no' # Enable when it's a common payment method

# Payments -  Cash on delivery
woo/woocommerce_cod_settings:
    enabled: 'no' # Enable when it's a common payment method

# Privacy Policy -  Checkout privacy policy
woo/woocommerce_checkout_privacy_policy_text: 'Seus dados pessoais serão utilizados para melhorar sua experiência neste site, para gerenciar o acesso à sua conta e para outras funcionalidades descritas em nossa [política de privacidade].' # Translate

# Privacy Policy - Registration privacy policy
woo/woocommerce_registration_privacy_policy_text: 'Seus dados pessoais serão usados para processar seu pedido, melhorar sua experiência neste site e para outras funcionalidades descritas em nossa [política de privacidade].' # Translate
