# Local Standards
woo/woocommerce_default_country: 'US' # Country code https://github.com/woocommerce/woocommerce/blob/master/i18n/countries.php
wp/date_format: 'm/d/Y' # "d/m/Y", "Y-m-d", "F j, Y" for December 1, 2020
wp/time_format: 'g:i A' # "H:i" for 24-hour clock, "g:i A" for 12-hour clock
wp/start_of_week: '7' # 1= Monday, 7=Sunday
wp/timezone_string: 'America/New_York' # Timezone string https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
wp/blog_charset: 'UTF-8'
wp/DEFAULT_WPLANG: 'en_US' # http://api.wordpress.org/translations/core/1.0/
woo/woocommerce_weight_unit: 'lbs' # Measurements weight unit kg, k, lbs, oz
woo/woocommerce_dimension_unit: 'in' # Measurements dimension unit m, cm, mm, in, yd

# Currency options
woo/woocommerce_currency: 'USD' # Currency https://www.iban.com/currency-codes.html
woo/woocommerce_currency_pos: 'left' # Currency position: left, left_space, right, right_space
woo/woocommerce_price_thousand_sep: ',' # Thousand separator
woo/woocommerce_price_decimal_sep: '.' # Decimal separator
woo/woocommerce_price_num_decimals: '2' # Number of decimals

# Payments - Direct bank transfer
woo/woocommerce_bacs_settings:
    enabled: 'no'

# Payments -  Cash on delivery
woo/woocommerce_cod_settings:
    enabled: 'no'

# Privacy Policy -  Checkout privacy policy
woo/woocommerce_checkout_privacy_policy_text: 'Your personal data will be used to process your order, support your experience throughout this website, and for other purposes described in our [privacy_policy].' # Translate

# Privacy Policy - Registration privacy policy
woo/woocommerce_registration_privacy_policy_text: 'Your personal data will be used to support your experience throughout this website, to manage access to your account, and for other purposes described in our [privacy_policy].' # Translate

# Metadata -- KEEP --
.woo/woocommerce_bacs_settings_format: serialized
.woo/woocommerce_cod_settings_format: serialized
# Metadata -- KEEP --
