name: Update Python Packages
on:
  schedule:
    # On the second of every month
    - cron: '0 0 2 * *'
  workflow_dispatch:
    # Manually trigger from the "Actions" tab

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v4
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash .github/workflows/poetry-update.sh
